version: '3.9'
services:
  mongo:
    image: mongo:6.0.4
    ports:
      - '27017'
    volumes:
      - mongoVolume:/data/db
    command: --quiet

  minio:
    image: minio/minio:RELEASE.2023-01-31T02-24-19Z
    ports:
      - '9000'
      - '9001'
    volumes:
      - minioVolume:/data
    command: server /data --console-address ":9001"

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/frontend/node_modules
      - /app/backend/node_modules
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/frontend/node_modules
      - /app/backend/node_modules
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - minio
    environment:
      - NODE_CONFIG_ENV=docker_compose

volumes:
  minioVolume:
  mongoVolume:
