version: '3.9'
services:
  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - frontend
      - backend

  mongo:
    image: mongo:6.0.4
    ports:
      - '27017'
    volumes:
      - mongoVolume:/data/db
    command: --quiet

  minio:
    image: minio/minio:RELEASE.2023-01-31T02-24-19Z
    ports:
      - '9000'
      - '9001'
    volumes:
      - minioVolume:/data
    command: server /data --console-address ":9001"

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - minio
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - NODE_CONFIG_ENV=docker_compose

volumes:
  minioVolume:
  mongoVolume:
