{{- if .Values.maildev.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: mail
  labels:
    name: mail
spec:
  ports:
    - port: 1080
      targetPort: 1080
      protocol: TCP
      name: http
    - port: {{ .Values.config.smtp.port }}
      targetPort: {{ .Values.config.smtp.port }}
      protocol: TCP
      name: smtp
  selector:
    name: maildev
{{- end }}