---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginxAuth.host }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.nginxAuth.host }}
  template:
    metadata:
      labels:
        name: {{ .Values.nginxAuth.host }}
    spec:
      containers:
      - name: {{ .Values.nginxAuth.host }}
        image: {{ .Values.nginxAuth.repository }}:{{ .Values.nginxAuth.tag }}
        resources:
          requests:
            cpu: 125m
            memory: 150Mi
        ports:
          - name: http
            containerPort: {{ .Values.nginxAuth.port }}
            protocol: TCP
        volumeMounts:
        - name: nginx-template
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf 
      volumes:
      - name: nginx-template
        configMap:
          name: {{ include "bailo.fullname" . }}-nginx-template