---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.registry.host }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.registry.host }}
  template:
    metadata:
      labels:
        name: {{ .Values.registry.host }}
    spec:
      containers:
      - name: {{ .Values.registry.host }}
        image: {{ .Values.registry.repository }}:{{ .Values.registry.tag }}
        resources:
          requests:
            cpu: 250m
            memory: 150Mi
          limits:
            cpu: 250m
            memory: 1000Mi
        ports:
          - name: http
            containerPort: {{ .Values.registry.port }}
            protocol: TCP
        env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: {{ .Values.registry.certDir }}/{{ .Values.registry.certFile }}
        - name: REGISTRY_HTTP_TLS_KEY
          value: {{ .Values.registry.certDir }}/{{ .Values.registry.keyFile }}
        - name: REGISTRY_STORAGE_S3_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: {{ include "bailo.fullname" . }}-minio
              key: root-user
        - name: REGISTRY_STORAGE_S3_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: {{ include "bailo.fullname" . }}-minio
              key: root-password
        - name: REGISTRY_AUTH
          value: "token"
        - name: REGISTRY_AUTH_TOKEN_REALM
          value: "https://{{ .Values.openshift.appPublicRoute }}/api/v1/registry_auth"
        - name: REGISTRY_AUTH_TOKEN_SERVICE
          value: "RegistryAuth"
        - name: REGISTRY_AUTH_TOKEN_ISSUER
          value: "RegistryIssuer"
        - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
          value: {{ .Values.registry.certDir }}/{{ .Values.registry.certFile }}
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "bailo.fullname" . }}-registry
              key: http-secret
        volumeMounts:
        - name: config-map-vol
          mountPath: /etc/docker/registry/config.yml
          subPath: config.yml
        - name: certs
          mountPath: {{ .Values.registry.certDir }}
      volumes:
      - name: config-map-vol
        configMap:
          name: {{ include "bailo.fullname" . }}-registry
          items:
          - key: registry.conf
            path: config.yml
      - name: certs
        secret:
          secretName: {{ include "bailo.fullname" . }}-certs
          items:
            - key: {{ .Values.nginxcert.cert }}
              path: {{ .Values.registry.certFile }}
            - key: {{ .Values.nginxcert.key }}
              path: {{ .Values.registry.keyFile }}