---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.registry.host }}
  labels:
    name: {{ .Values.registry.host }}
    {{- include "bailo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.registry.port }}
      targetPort: {{ .Values.registry.port }}
      protocol: TCP
      name: tcp
  selector:
    name: {{ .Values.registry.host }}
