{{- $registryPasswordValue := (randAlpha 16) | b64enc | quote }}
{{- $registrySecret := (lookup "v1" "Secret" .Release.Namespace "bailo-registry") }}
{{- if $registrySecret}}
{{- $registryPasswordValue = index $registrySecret.data "http-secret" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bailo.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  http-secret: {{ $registryPasswordValue }}
