---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bailo.fullname" . }}
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bailo.selectorLabels" . | nindent 6}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bailo.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: bailo-builder
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          #image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "bailo.fullname" . }}-minio
                  key: root-user
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "bailo.fullname" . }}-minio
                  key: root-password
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "bailo.fullname" . }}-mongodb
                  key: mongodb-passwords
            - name: MONGO_CONNECTION_URI
              value: {{ include "bailo.mongoConnectionURI" . | quote }}
            - name: SCHEMA_SETUP_SCRIPT
              value: {{ .Values.config.schema.script }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config/production.js
              subPath: production.js
            - name: config
              mountPath: /app/config/custom-environment-variables.js
              subPath: custom-environment-variables.js
            - name: certs
              mountPath: /app/certs
            - name: temp
              mountPath: /tmp
            - name: cache
              mountPath: /app/.next/cache
            - name: certs
              mountPath: /usr/local/share/ca-certificates/bailo.pem
              subPath: cert.pem
            - name: stroom
              mountPath: /app/logs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "bailo.fullname" . }}-config
            items:
              - key: production.js
                path: production.js
              - key: custom-environment-variables.js
                path: custom-environment-variables.js
        - name: certs
          secret:
            secretName: {{ include "bailo.fullname" . }}-certs
            items:
              - key: cert.pem
                path: cert.pem
              - key: key.pem
                path: key.pem
        - name: temp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: stroom
          emptyDir: {}
