apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bailo.fullname" . }}-certs
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "certs/**.pem").AsSecrets | indent 2 }}